# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\garbe\OneDrive\Documents\GitHub\BitLords-Inc\ToDo_List.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow
import sys

from PyQt5 import QtCore, QtGui


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.add_pushButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.add_it())
        self.add_pushButton.setGeometry(QtCore.QRect(660, 490, 93, 28))
        self.add_pushButton.setObjectName("add_pushButton")

        self.newTask_lineEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.newTask_lineEdit.setGeometry(QtCore.QRect(470, 490, 171, 31))
        self.newTask_lineEdit.setObjectName("newTask_textEdit")

        self.myTasks_listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.myTasks_listWidget.setGeometry(QtCore.QRect(130, 70, 531, 331))
        self.myTasks_listWidget.setObjectName("myTasks_listWidget")
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    #Adding Item to the List
    def add_it(self):
        #grab the task
        item = self.newTask_lineEdit.toPlainText()

        #add to list
        self.myTasks_listWidget.addItem(item)

        #clear test
        self.newTask_lineEdit.setText("")


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.add_pushButton.setText(_translate("MainWindow", "Add Task"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())